name: nicstore
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  amplify_api: ^1.4.0
  amplify_datastore: ^1.4.2
  amplify_flutter: ^1.4.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
